inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - 'bin/*'
    - 'Rakefile'
    - '**/*.rake'
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 80

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
